insert into country (url_id, cn_name, en_name, state) values (11698, '阿富汗',  'Afghanistan', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (11213, '阿联酋',  'United Arab Emirates', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (16674, '阿曼',  'Sultanate of Oman', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (31369, '阿塞拜疆',  'Azerbaijan', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (11697, '巴基斯坦',  'Pakistan', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (32105, '巴勒斯坦',  'Palestine', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (15519, '巴林',  'Bahrain', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10711, '不丹',  'Bhutan', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (11780, '朝鲜',  'North Korea', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (29700, '东帝汶',  'East Timor', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10067, '菲律宾',  'Philippines', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10234, '格鲁吉亚',  'Georgia', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (17393, '哈萨克斯坦',  'The Republic of Kazakhstan', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10184, '韩国',  'Korea', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (57194, '吉尔吉斯斯坦',  'Kyrgyzstan', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10070, '柬埔寨',  'Cambodia', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (12035, '卡塔尔',  'The State of Qatar', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (21762, '科威特',  'The State of Kuwait', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10820, '老挝',  'Laos', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (12028, '黎巴嫩',  'Lebanon', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10101, '马尔代夫',  'Maldives', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10097, '马来西亚',  'Malaysia', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (14293, '蒙古',  'Mongolia', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (14783, '孟加拉国',  'Bangladesh', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10179, '缅甸',  'Myanmar', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10069, '尼泊尔',  'Nepal', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10183, '日本',  'Japan', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (11765, '沙特阿拉伯',  'Saudi Arabia', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (11058, '斯里兰卡',  'Sri Lanka', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (24254, '塔吉克斯坦',  'Tajikistan', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10083, '泰国',  'Thailand', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (35250, '土库曼斯坦',  'Turkmenistan', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10753, '文莱',  'Brunei Darussalam', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (48878, '乌兹别克斯坦',  'The Republic of Uzbekistan', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10754, '新加坡',  'Singapore', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (11217, '叙利亚',  'The Syrian Arab Republic', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (32160, '亚美尼亚',  'The Republic of Armenia', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (21498, '也门',  'The Republic of Yemen', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (28466, '伊拉克',  'Iraq', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (11699, '伊朗',  'Iran', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10605, '以色列',  'Israel', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10182, '印度',  'India', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10181, '印度尼西亚',  'Indonesia', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (11221, '约旦',  'Jordan', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (10180, '越南',  'Vietnam', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (21536, '中国',  'China', '亚洲');
insert into country (url_id, cn_name, en_name, state) values (57151, '安提瓜和巴布达', 'Antigua and Barbuda', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (57152, '巴巴多斯', 'Barbados', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (11943, '巴哈马', 'Bahamas', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (25229, '巴拿马', 'Panama', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (32796, '伯利兹', 'Belize', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (25756, '多米尼加', 'Dominican Republic', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (57153, '多米尼克', 'Dominica', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (24412, '哥斯达黎加', 'Costa Rica', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (57154, '格林纳达', 'Grenada', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (11684, '古巴', 'Cuba', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (12029, '海地', 'Haiti', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (30877, '洪都拉斯', 'Republic of Honduras', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (10177, '加拿大', 'Canada', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (10062, '美国', 'United States of America', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (11656, '墨西哥', 'The United Mexican States', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (57155, '尼加拉瓜', 'Nicaragua', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (57156, '萨尔瓦多', 'El Salvador', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (57157, '圣基茨和尼维斯', 'Saint Kitts and Nevis', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (57158, '圣卢西亚', 'Saint Lucia', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (57159, '圣文森特和格林纳丁斯', 'Saint Vincent and the Grenadines', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (57160, '特立尼达和多巴哥', 'Trinidad and Tobago', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (17493, '危地马拉', 'Guatemala', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (12030, '牙买加', 'Jamaica', '北美洲');
insert into country (url_id, cn_name, en_name, state) values (10159, '阿根廷', 'Argentina', '南美洲');
insert into country (url_id, cn_name, en_name, state) values (38471, '巴拉圭', 'Paraguay', '南美洲');
insert into country (url_id, cn_name, en_name, state) values (10160, '巴西', 'Brazil', '南美洲');
insert into country (url_id, cn_name, en_name, state) values (11005, '秘鲁', 'The Republic of Peru', '南美洲');
insert into country (url_id, cn_name, en_name, state) values (13484, '玻利维亚', 'Bolivia', '南美洲');
insert into country (url_id, cn_name, en_name, state) values (18225, '厄瓜多尔', 'Ecuador', '南美洲');
insert into country (url_id, cn_name, en_name, state) values (10955, '哥伦比亚', 'Colombia', '南美洲');
insert into country (url_id, cn_name, en_name, state) values (57187, '圭亚那', 'Guyana', '南美洲');
insert into country (url_id, cn_name, en_name, state) values (36914, '苏里南', 'The Republic of Suriname', '南美洲');
insert into country (url_id, cn_name, en_name, state) values (15757, '委内瑞拉', 'Bolivarian Republic of Venezuela', '南美洲');
insert into country (url_id, cn_name, en_name, state) values (12104, '乌拉圭', 'The Oriental Republic of Uruguay', '南美洲');
insert into country (url_id, cn_name, en_name, state) values (10992, '智利', 'Republic of Chile', '南美洲');
insert into country (url_id, cn_name, en_name, state) values (24844, '阿尔巴尼亚', 'The Republic of Albania', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11131, '爱尔兰', 'Ireland', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11631, '爱沙尼亚', 'The Republic of Estonia', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (19744, '安道尔', 'Andorra', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10175, '奥地利', 'Austria', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (28072, '白俄罗斯', 'Belarus', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (38605, '保加利亚', 'The Republic of Bulgaria', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11105, '比利时', 'Belgium', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10549, '冰岛', 'Iceland', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11570, '波黑', 'Bosnia and Herzegovina', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11147, '波兰', 'Poland', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11157, '丹麦', 'Denmark', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10176, '德国', 'Germany', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10300, '俄罗斯', 'Russia', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10171, '法国', 'France', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11614, '梵蒂冈', 'Vatican City State', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10448, '芬兰', 'Finland', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11099, '荷兰', 'Holland', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (57192, '黑山', 'Montenegro', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10174, '捷克', 'Czech', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (57193, '科索沃', 'The Republic of Kosovo', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11853, '克罗地亚', 'Croatia', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (18897, '拉脱维亚', 'Latvia', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (18942, '立陶宛', 'Lithuania', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11097, '列支敦士登', 'Liechtenstein', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11098, '卢森堡', 'The Grand Duchy of Luxembourg', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (30071, '罗马尼亚', 'Romania', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (16501, '马耳他', 'Malta', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (38921, '马其顿', 'Macedonia', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (24945, '摩尔多瓦', 'The Republicof Moldova', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11140, '摩纳哥', 'The Principality of Monaco', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11160, '挪威', 'Norway', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10172, '葡萄牙', 'Portugal', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10214, '瑞典', 'The Kingdom of Sweden', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10169, '瑞士', 'Switzerland', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (26909, '塞尔维亚', 'The Republic of Serbia', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (16648, '塞浦路斯', 'Cyprus', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (15077, '圣马力诺', 'The Republic of San Marino', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11153, '斯洛伐克', 'Slovakia', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11852, '斯洛文尼亚', 'The Republic of Slovenia', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10053, '土耳其', 'Turkey', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (15693, '乌克兰', 'Ukraine', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10173, '西班牙', 'Spain', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10168, '希腊', 'Greece', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (11094, '匈牙利', 'Hungary', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10051, '意大利', 'Italy', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10122, '英国', 'United Kingdom', '欧洲');
insert into country (url_id, cn_name, en_name, state) values (10178, '埃及', 'Egypt', '非洲');
insert into country (url_id, cn_name, en_name, state) values (12858, '埃塞俄比亚', 'Ethiopia', '非洲');
insert into country (url_id, cn_name, en_name, state) values (22047, '安哥拉', 'The Republic of Angola', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57170, '贝宁', 'Benin', '非洲');
insert into country (url_id, cn_name, en_name, state) values (15534, '博茨瓦纳', 'Botswana', '非洲');
insert into country (url_id, cn_name, en_name, state) values (56531, '布基纳法索', 'Burkina Faso', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57171, '布隆迪', 'Burundi', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57172, '赤道几内亚', 'Equatorial Guinea', '非洲');
insert into country (url_id, cn_name, en_name, state) values (17958, '多哥', 'Togo', '非洲');
insert into country (url_id, cn_name, en_name, state) values (19760, '厄立特里亚', 'The State of Eritrea', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57173, '佛得角', 'Cape Verde', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57174, '冈比亚', 'Gambia', '非洲');
insert into country (url_id, cn_name, en_name, state) values (12031, '刚果', 'The Republic of Congo', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57175, '刚果民主共和国', 'Democratic Republic of the Congo', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57176, '吉布提', 'Djibouti', '非洲');
insert into country (url_id, cn_name, en_name, state) values (32815, '几内亚', 'The Republic of Guinea', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57177, '几内亚比绍', 'Guinea-Bissau', '非洲');
insert into country (url_id, cn_name, en_name, state) values (11706, '加纳', 'Ghana', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57178, '加蓬', 'Gabon', '非洲');
insert into country (url_id, cn_name, en_name, state) values (11752, '津巴布韦', 'Zimbabwe', '非洲');
insert into country (url_id, cn_name, en_name, state) values (27636, '喀麦隆', 'Cameroon', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57179, '科摩罗', 'Comoros', '非洲');
insert into country (url_id, cn_name, en_name, state) values (13122, '科特迪瓦', 'Ivory Coast', '非洲');
insert into country (url_id, cn_name, en_name, state) values (10029, '肯尼亚', 'Kenya', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57180, '莱索托', 'Lesotho', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57181, '利比里亚', 'Liberia', '非洲');
insert into country (url_id, cn_name, en_name, state) values (16746, '利比亚', 'State of Libya', '非洲');
insert into country (url_id, cn_name, en_name, state) values (22478, '留尼旺', 'Réunion', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57182, '卢旺达', 'Rwanda', '非洲');
insert into country (url_id, cn_name, en_name, state) values (17439, '马达加斯加', 'Madagascar', '非洲');
insert into country (url_id, cn_name, en_name, state) values (29615, '马拉维', 'The Republic of Malawi', '非洲');
insert into country (url_id, cn_name, en_name, state) values (12036, '马里', 'The Republic of Mali', '非洲');
insert into country (url_id, cn_name, en_name, state) values (11761, '毛里求斯', 'Mauritius', '非洲');
insert into country (url_id, cn_name, en_name, state) values (18450, '毛里塔尼亚', 'The Islamic Republic of Mauritania', '非洲');
insert into country (url_id, cn_name, en_name, state) values (12033, '摩洛哥', 'Morocco', '非洲');
insert into country (url_id, cn_name, en_name, state) values (11753, '莫桑比克', 'Mozambique', '非洲');
insert into country (url_id, cn_name, en_name, state) values (10762, '纳米比亚', 'Namibia', '非洲');
insert into country (url_id, cn_name, en_name, state) values (10455, '南非', 'South Africa', '非洲');
insert into country (url_id, cn_name, en_name, state) values (19955, '南苏丹', 'Republic of South Sudan', '非洲');
insert into country (url_id, cn_name, en_name, state) values (12027, '尼日尔', 'Niger', '非洲');
insert into country (url_id, cn_name, en_name, state) values (21111, '尼日利亚', 'Federal Republic of Nigeria', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57183, '塞拉利昂', 'Sierra leone', '非洲');
insert into country (url_id, cn_name, en_name, state) values (12026, '塞内加尔', 'Senegal', '非洲');
insert into country (url_id, cn_name, en_name, state) values (16827, '塞舌尔', 'Seychelles', '非洲');
insert into country (url_id, cn_name, en_name, state) values (32925, '圣多美和普林西比', 'Sao Tome and Principe', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57184, '斯威士兰', 'Swaziland', '非洲');
insert into country (url_id, cn_name, en_name, state) values (15123, '苏丹', 'Sudan', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57185, '索马里', 'Somalia', '非洲');
insert into country (url_id, cn_name, en_name, state) values (10818, '坦桑尼亚', 'The United Republic of Tanzania', '非洲');
insert into country (url_id, cn_name, en_name, state) values (11604, '突尼斯', 'Tunisia', '非洲');
insert into country (url_id, cn_name, en_name, state) values (12034, '乌干达', 'Uganda', '非洲');
insert into country (url_id, cn_name, en_name, state) values (57186, '西撒哈拉', 'Western Sahara', '非洲');
insert into country (url_id, cn_name, en_name, state) values (11751, '赞比亚', 'Zambia', '非洲');
insert into country (url_id, cn_name, en_name, state) values (28359, '乍得', 'Chad', '非洲');
insert into country (url_id, cn_name, en_name, state) values (10689, '中非', 'The Central African Republic', '非洲');
insert into country (url_id, cn_name, en_name, state) values (10202, '澳大利亚', 'Australia', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (12647, '巴布亚新几内亚', 'Papua New Guinea', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (10344, '大溪地', 'Tahiti', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (11044, '斐济', 'Fiji', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (19016, '关岛', 'Guam', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (57161, '基里巴斯', 'Kiribati', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (57167, '库克群岛', 'Cook Islands', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (57162, '马绍尔群岛', 'Marshall Islands', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (57163, '密克罗尼西亚联邦', 'Micronesia', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (57166, '瑙鲁', 'Nauru', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (57168, '纽埃', 'Niue', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (15911, '帕劳', 'Palau', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (54998, '萨摩亚', 'Samoa', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (24406, '所罗门群岛', 'Solomon Islands', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (17753, '汤加', 'The Kingdom of Tonga', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (57164, '图瓦卢', 'Tuvalu', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (52088, '瓦努阿图', 'Republic of Vanuatu', '大洋洲');
insert into country (url_id, cn_name, en_name, state) values (10544, '新西兰', 'New Zealand', '大洋洲');
